import React from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { Message, MessageRole, MessageType } from '../types';
import { User, Bot, AlertCircle, Download } from 'lucide-react';

interface MessageBubbleProps {
  message: Message;
}

const MessageBubble: React.FC<MessageBubbleProps> = ({ message }) => {
  const isUser = message.role === MessageRole.USER;

  return (
    <div className={`flex w-full mb-6 ${isUser ? 'justify-end' : 'justify-start'}`}>
      <div className={`flex max-w-[85%] md:max-w-[75%] ${isUser ? 'flex-row-reverse' : 'flex-row'} gap-3`}>
        
        {/* Avatar */}
        <div className={`flex-shrink-0 w-8 h-8 rounded-full flex items-center justify-center ${isUser ? 'bg-primary' : 'bg-accent'}`}>
          {isUser ? <User size={16} className="text-white" /> : <Bot size={16} className="text-white" />}
        </div>

        {/* Content Bubble */}
        <div className={`flex flex-col ${isUser ? 'items-end' : 'items-start'}`}>
          <div 
            className={`px-4 py-3 rounded-2xl shadow-md ${
              isUser 
                ? 'bg-primary text-white rounded-tr-none' 
                : 'bg-dark-lighter text-slate-200 border border-slate-700 rounded-tl-none'
            }`}
          >
            {message.type === MessageType.TEXT && (
              <div className="markdown-body text-sm md:text-base leading-relaxed">
                <ReactMarkdown remarkPlugins={[remarkGfm]}>
                  {message.content}
                </ReactMarkdown>
              </div>
            )}

            {message.type === MessageType.IMAGE && (
              <div className="flex flex-col gap-2">
                <img 
                  src={message.content} 
                  alt="Generated content" 
                  className="rounded-lg max-w-full h-auto border border-slate-600"
                />
                <a 
                  href={message.content} 
                  download={`suvidha-gen-${message.id}.jpg`}
                  className="flex items-center gap-2 text-xs text-slate-400 hover:text-white transition-colors mt-1"
                >
                  <Download size={14} /> Download Image
                </a>
              </div>
            )}

            {message.type === MessageType.VIDEO && (
              <div className="flex flex-col gap-2">
                <video 
                  controls 
                  className="rounded-lg max-w-full h-auto border border-slate-600 w-[400px]"
                  src={message.content}
                >
                  Your browser does not support the video tag.
                </video>
                <div className="text-xs text-slate-400 mt-1">
                  Video generated by Veo
                </div>
              </div>
            )}

            {message.type === MessageType.ERROR && (
              <div className="flex items-center gap-2 text-red-400">
                <AlertCircle size={18} />
                <span>{message.content}</span>
              </div>
            )}
          </div>
          
          {/* Timestamp */}
          <span className="text-[10px] text-slate-500 mt-1 px-1">
            {new Date(message.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
          </span>
        </div>
      </div>
    </div>
  );
};

export default MessageBubble;
